export const CvActionTypes = {
  LOADING_API: 'LOADING_API',
  LOADING_UPDATE: 'LOADING_UPDATE',
  LOAD_CV_START: 'LOAD_CV_START',
  LOAD_CV_FINISH: 'LOAD_CV_FINISH',
  LOAD_CV_FAILURE: 'LOAD_CV_FAILURE',
  UPDATE_CV_START: 'UPDATE_CV_START',
  UPDATE_CV_FINISH: 'UPDATE_CV_FINISH',
  UPDATE_CV_FAILURE: 'UPDATE_CV_FAILURE',
  UPLOAD_CV_IMAGE_START: 'UPLOAD_CV_IMAGE_START',
  UPLOAD_CV_IMAGE_END: 'UPLOAD_CV_IMAGE_END',
  UPLOAD_CV_IMAGE_FAILURE: 'UPLOAD_CV_IMAGE_FAILURE',
};
